name: 'Mirror Mercurial (hg) repository to GitHub'
description: |-
  Mirror Mercurial (hg) repository to GitHub.
inputs:
  source-hg-repo-url:
    description: ''
    required: true
#  destination-git-domain:
#    description: ''
#    default: 'github.com'
#    required: false
#  destination-git-scheme:
#    description: ''
#    default: 'https'
#    required: false
  destination-git-repo-owner:
    description: ''
    required: true
  destination-git-repo-name:
    description: ''
    required: true
  destination-git-personal-token:
    description: ''
    required: true
  force-push:
    description: ''
    required: false
    default: 'false'
  repo-style:
    description: 'normal or pypy-style'
    required: false
    default: 'normal'

branding:
  icon: 'arrow-up-circle'
  color: 'blue'

runs:
  using: 'node16'
  main: 'dist/index.js'
#  post: 'dist/post/index.js'
