name: test

on:
  workflow_dispatch:
  push:
  pull_request:


jobs:
  mirror-normal:
    runs-on: ubuntu-latest
    name: mirror hg repo
    permissions:
      contents: read  # This is required for actions/checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'
      - run: npm install
      - run: npm run build

      - name: test mirror action 1
        uses: ./ # Uses an action in the root directory
        with:
          source-hg-repo-url: 'https://foss.heptapod.net/pypy/cffi'
          destination-git-repo-owner: 'mozillazg'
          destination-git-repo-name: 'cffi'
          destination-git-personal-token: '${{ secrets.PERSONAL_GIT_TOKEN }}'

      - name: test mirror action 2
        uses: ./ # Uses an action in the root directory
        with:
          source-hg-repo-url: 'http://hg.code.sf.net/p/ruamel-yaml/code'
          destination-git-repo-owner: 'mozillazg'
          destination-git-repo-name: 'ruamel-yaml'
          destination-git-personal-token: '${{ secrets.PERSONAL_GIT_TOKEN }}'

      - name: test mirror action 3
        uses: ./ # Uses an action in the root directory
        with:
          source-hg-repo-url: 'http://hg.code.sf.net/p/ruamel-yaml-clib/code'
          destination-git-repo-owner: 'mozillazg'
          destination-git-repo-name: 'ruamel-yaml-clib'
          destination-git-personal-token: '${{ secrets.PERSONAL_GIT_TOKEN }}'

  mirror-pypy:
    runs-on: ubuntu-latest
    name: mirror pypy
    permissions:
      contents: read  # This is required for actions/checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'
      - run: npm install
      - run: npm run build

      - name: test mirror pypy
        uses: ./ # Uses an action in the root directory
        with:
          source-hg-repo-url: 'https://foss.heptapod.net/pypy/pypy'
          destination-git-repo-owner: 'mozillazg'
          destination-git-repo-name: 'pypy-mirror'
          destination-git-personal-token: '${{ secrets.PERSONAL_GIT_TOKEN }}'
          repo-style: 'pypy-style'
