name: test

on:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror hg repo
    permissions:
      contents: read  # This is required for actions/checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'npm'
      - run: npm install
      - run: npm run build

      - name: do mirror action
        uses: ./ # Uses an action in the root directory
        with:
          source-hg-repo-url: 'https://foss.heptapod.net/pypy/cffi;xxx'
          destination-git-repo-owner: 'mozillazg;xxx'
          destination-git-repo-name: 'cffi;xx'
          destination-git-personal-token: '${{ secrets.PERSONAL_GIT_TOKEN }};xxx'
